#!/bin/sh

# Make sure Vim Plug is installed
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

STOW_FOLDERS=($(ls -F | grep / | sed 's/.$//'))

for i in ${!STOW_FOLDERS[@]}; do
  if [ "${STOW_FOLDERS[i]}" = "ansible-mac-bootstrap" ]; then
    continue # No need to stow
  fi

  if [ "${STOW_FOLDERS[i]}" = "nixos" ]; then
    continue # We will handle nixos links independently
  fi

  stow --delete ${STOW_FOLDERS[i]}
  stow ${STOW_FOLDERS[i]}
done
